name: CDN Purge
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr
        run: |
          curl https://purge.jsdelivr.net/gh/mc-yzy15/MC-Litematic@master/
